name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "19 */7 * * *"
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  "lts/*" # Adjust as needed

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install and Crawl
        run: |
          cd crawl
          yarn install
          yarn all

      - name: Install and Build UI
        run: |
          cd ui
          yarn install
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
